import '02_01_QuizQA.dart';

class QuizQ_List {
  Map<String, QuizQ> list = {
    '1': QuizQ(
        QID: '1',
        Picture: 'images/Yoiti.jpeg',
        problem: '園内に1km以上の桜並木があることで有名な、神田川沿いに東西に広がる長細い公園は、つぎのうちどれ？',
        Select1: '江戸川公園',
        Select2: '礫川公園',
        Select3: '肥後細川庭園',
        Select4: '文京宮下公園',
        PicturePtn: '0'),
    '2': QuizQ(
        QID: '2',
        Picture: 'images/Rikito.jpg',
        problem:
            '茗荷谷駅近くの林泉寺境内には、ある「めずらしいこと」をされている地蔵が祀られています。その「めずらしいこと」とは次のうちどれ？',
        Select1: '水をかけられている',
        Select2: '縛られてる',
        Select3: '針を刺されている',
        Select4: '黒く塗られている',
        PicturePtn: '1'),
    '3': QuizQ(
        QID: '3',
        Picture: 'images/question/tate2.jpg',
        problem:
            '四季折々の魅力がある文京区には、「文京花の５大まつり」というお祭りがあります。その花は、さくら、つつじ、あじさい、うめ、あと一つは何でしょうか？',
        Select1: 'きく',
        Select2: 'ひまわり',
        Select3: 'ばら',
        Select4: 'ゆり',
        PicturePtn: '0'),
    '4': QuizQ(
        QID: '4',
        Picture: 'images/question/tate2.jpg',
        problem:
            '本郷給水所の上方にある本郷給水所公苑には、和風庭園と西洋庭園の2つから成り立っています。そのうち西洋庭園には、約52種、300株のバラが植えられており、見頃が年2回あるそうです。その見頃とは、5月といつでしょうか？',
        Select1: '7月',
        Select2: '8月',
        Select3: '9月',
        Select4: '10月',
        PicturePtn: '0'),
    '5': QuizQ(
        QID: '5',
        Picture: 'images/question/tate2.jpg',
        problem:
            '約80年以上の歴史がある「本郷 三原堂」。時代に合わせて、お菓子を刷新していますが、創業当初からそのままのお菓子があります。それはどれでしょうか？',
        Select1: '大学最中',
        Select2: '本郷焼（どら焼き）',
        Select3: '塩せんべい',
        Select4: '栗まんじゅう',
        PicturePtn: '0'),
    '6': QuizQ(
        QID: '6',
        Picture: 'images/question/tate2.jpg',
        problem: '後楽園と茗荷谷の間の住宅街にある庚申坂。実は、別名もあるそう。その別名とは？',
        Select1: '葛坂',
        Select2: '鉄砲坂',
        Select3: '切支丹坂',
        Select4: '稲荷坂',
        PicturePtn: '0'),
    '7': QuizQ(
        QID: '7',
        Picture: 'images/question/tate2.jpg',
        problem: '東京10社の一つである根津神社では、1年に3回ほどお祭りがあります。4季のうち、お祭りがない時期はいつでしょうか。',
        Select1: '春',
        Select2: '夏',
        Select3: '秋',
        Select4: '冬',
        PicturePtn: '0'),
    '8': QuizQ(
        QID: '8',
        Picture: 'images/question/tate2.jpg',
        problem: '東京10社の一つの白山神社。とあるご利益でも有名ですが、そのご利益とは何でしょうか？',
        Select1: '子宝',
        Select2: '復縁',
        Select3: '商売繁盛',
        Select4: '才能開花',
        PicturePtn: '0'),
    '9': QuizQ(
        QID: '9',
        Picture: 'images/question/tate2.jpg',
        problem:
            '音楽イベントにも使われるホールや区民施設、区役所などの公共機関からなる総合施設、文京区シビックセンター。その25階には展望ラウンジがあります。その展望ラウンジから見れるものはどれでしょうか。',
        Select1: '富士山',
        Select2: '筑波山',
        Select3: 'スカイツリー',
        Select4: '全部',
        PicturePtn: '0'),
    '10': QuizQ(
        QID: '10',
        Picture: 'images/question/tate2.jpg',
        problem: '文京区は自転車のシェアリング事業を営んでいます。その事業で取り扱っている自転車は文京区内だけで何台あるでしょうか？',
        Select1: '100台',
        Select2: '300台',
        Select3: '500台',
        Select4: '800台',
        PicturePtn: '0'),
    '11': QuizQ(
        QID: '11',
        Picture: 'images/question/tate2.jpg',
        problem: '小石川の福聚院に祀られている地蔵には、とある食べ物が大量にお供えされています。その食べ物とは何でしょうか？',
        Select1: 'とうがらし',
        Select2: 'そらまめ',
        Select3: 'あずき',
        Select4: 'きゅうり',
        PicturePtn: '0'),
    '12': QuizQ(
        QID: '12',
        Picture: 'images/question/tate2.jpg',
        problem:
            '2019年に文の京都市景観賞のふるさと景観賞を受賞したしろへび坂。その坂上からは建物の狭間にある日本の有名な建物が見えます。それは何でしょうか？',
        Select1: 'スカイツリー',
        Select2: '東京タワー',
        Select3: '六本木ヒルズ',
        Select4: '東京ドーム',
        PicturePtn: '0'),
    '13': QuizQ(
        QID: '13',
        Picture: 'images/question/tate2.jpg',
        problem: '千駄木にある須藤公園には、一般的な公園にはない、ある珍しいものがあります。それは何でしょうか？',
        Select1: 'ひまわり畑',
        Select2: '滝',
        Select3: 'トランポリン',
        Select4: '釣り堀',
        PicturePtn: '0'),
    '14': QuizQ(
        QID: '14',
        Picture: 'images/question/tate2.jpg',
        problem: '本郷三丁目の交差点から40ｍほどに見返り坂・見送り坂という坂があります。その見送る相手とは、次のうち誰でしょうか？',
        Select1: '花婿',
        Select2: '兵士',
        Select3: '罪人',
        Select4: '死人',
        PicturePtn: '0'),
    '15': QuizQ(
        QID: '15',
        Picture: 'images/question/tate2.jpg',
        problem: '東京ドームシティの観覧車40台のうち、8台だけとあるものがついています。そのあるものとは何でしょうか？',
        Select1: 'カラオケ',
        Select2: 'ミラーボール',
        Select3: 'プリクラ',
        Select4: '望遠鏡',
        PicturePtn: '0'),
    '16': QuizQ(
        QID: '16',
        Picture: 'images/question/tate2.jpg',
        problem: '本郷三丁目駅のほど近くにある「本郷弓町のクス」と呼ばれてるクスノキの樹齢は、次のうちどれでしょうか？',
        Select1: '200年',
        Select2: '300年',
        Select3: '500年',
        Select4: '600年',
        PicturePtn: '0'),
    '17': QuizQ(
        QID: '17',
        Picture: 'images/question/tate2.jpg',
        problem: '東京三名園は「小石川庭園（文京区）」「浜離宮恩賜庭園（中央区）」と、あと一つは何でしょうか？',
        Select1: '六義園',
        Select2: '肥後細川庭園',
        Select3: '占春園',
        Select4: '後楽園',
        PicturePtn: '0'),
    '18': QuizQ(
        QID: '18',
        Picture: 'images/question/tate2.jpg',
        problem: '狂言などが上演される能楽堂は、都内にも数カ所ありますが、文京区にある能楽堂の名前は、次のうちどれでしょうか？',
        Select1: '国立能楽堂',
        Select2: '矢来能楽堂',
        Select3: 'セルリアンタワー能楽堂',
        Select4: '宝生能楽堂',
        PicturePtn: '0'),
    '19': QuizQ(
        QID: '19',
        Picture: 'images/question/tate2.jpg',
        problem: '文京区内には様々な駅がありますが、JRの駅はいくつあるでしょうか？',
        Select1: '0駅',
        Select2: '1駅',
        Select3: '2駅',
        Select4: '3駅',
        PicturePtn: '0'),
    '20': QuizQ(
        QID: '20',
        Picture: 'images/question/tate2.jpg',
        problem: '文京区の消防署で、存在しない消防署はどれでしょうか？',
        Select1: '大塚消防署',
        Select2: '本郷消防署',
        Select3: '小石川消防署',
        Select4: 'どれも存在する',
        PicturePtn: '0'),
    '21': QuizQ(
        QID: '21',
        Picture: 'images/question/tate2.jpg',
        problem: '文京区は元々２つの区からできています。一つは本郷区ですが、もう一つは何区でしょうか？',
        Select1: '根津区',
        Select2: '白山区',
        Select3: '千駄木区',
        Select4: '小石川区',
        PicturePtn: '0'),
    '22': QuizQ(
        QID: '22',
        Picture: 'images/question/tate2.jpg',
        problem:
            '東京大学の赤門の色は、ある将軍の娘をお嫁として迎え入れる際に赤に塗りつぶされたと言われています。この将軍とは、どの家柄でしょうか？',
        Select1: '北条家',
        Select2: '織田家',
        Select3: '豊臣家',
        Select4: '徳川家',
        PicturePtn: '0'),
    '23': QuizQ(
        QID: '23',
        Picture: 'images/question/tate2.jpg',
        problem: '東京大学内の坂や道には名前がついていますが、実際に存在するものはどれでしょうか？',
        Select1: '合格通り',
        Select2: '秀才通り',
        Select3: '勉強坂',
        Select4: '勤勉坂',
        PicturePtn: '0'),
    '24': QuizQ(
        QID: '24',
        Picture: 'images/question/tate2.jpg',
        problem: '東京大学付近に「おばけ階段」と呼ばれる階段があります。名前に「おばけ」とついている理由は何でしょうか？',
        Select1: '周壁のシミがおばけに見える',
        Select2: '影ができない',
        Select3: '体が重くなる',
        Select4: '上りと下りで段数が異なる',
        PicturePtn: '0'),
    '25': QuizQ(
        QID: '25',
        Picture: 'images/question/tate2.jpg',
        problem: '文京区内で唯一、蛍が見れる場所があります。そこはどこでしょうか？',
        Select1: '六義園',
        Select2: '椿山荘',
        Select3: '須藤公園',
        Select4: '小石川植物園',
        PicturePtn: '0'),
    '26': QuizQ(
        QID: '26',
        Picture: 'images/question/tate2.jpg',
        problem:
            '根津神社の一角にある、ある水飲み台。それは森鴎外が日露戦争の戦利品として、奉納したものが使われているのですが、それは何でしょうか？',
        Select1: '戦車',
        Select2: '三八式歩兵銃',
        Select3: '戦艦',
        Select4: '砲台',
        PicturePtn: '0'),
    '27': QuizQ(
        QID: '27',
        Picture: 'images/question/tate2.jpg',
        problem: '「ラジオ体操発祥の地」と言われ、銅像も建てられている公園は次のうちどれでしょうか？',
        Select1: '教育の森公園',
        Select2: '大塚公園',
        Select3: '小日向公園',
        Select4: '動坂公園',
        PicturePtn: '0'),
    '28': QuizQ(
        QID: '28',
        Picture: 'images/question/tate2.jpg',
        problem: '区内で唯一、関東の駅百選に選ばれた駅があります。それは何駅でしょうか？',
        Select1: '茗荷谷駅',
        Select2: '東大前駅',
        Select3: '本駒込駅',
        Select4: '後楽園駅',
        PicturePtn: '0'),
    '29': QuizQ(
        QID: '29',
        Picture: 'images/question/tate2.jpg',
        problem: '東京23区で坂の数が最も多い区は何区でしょうか？',
        Select1: '港区',
        Select2: '文京区',
        Select3: '杉並区',
        Select4: '足立区',
        PicturePtn: '0'),
    '30': QuizQ(
        QID: '30',
        Picture: 'images/question/tate2.jpg',
        problem: '夏目漱石が文京区で執筆した処女作は、次のうちどれでしょうか？',
        Select1: 'こころ',
        Select2: '吾輩は猫である',
        Select3: '三四郎',
        Select4: '坊ちゃん',
        PicturePtn: '0'),
    '31': QuizQ(
        QID: '31',
        Picture: 'images/question/tate2.jpg',
        problem: '文京区と姉妹都市を提携しているカイザースラウテルン市があるのは、次のうちどの国でしょうか？',
        Select1: 'ドイツ',
        Select2: 'フランス',
        Select3: 'トルコ',
        Select4: 'オーストリア',
        PicturePtn: '0'),
    '32': QuizQ(
        QID: '32',
        Picture: 'images/question/tate2.jpg',
        problem: '5,000円札に印字されている樋口一葉。彼女の職業は次のうちどれでしょうか。',
        Select1: '小説家',
        Select2: '看護師',
        Select3: '革命家',
        Select4: '建築家',
        PicturePtn: '0'),
    '33': QuizQ(
        QID: '33',
        Picture: 'images/question/tate2.jpg',
        problem: '源覚寺の閻魔さまの別名は、何閻魔でしょうか？',
        Select1: 'あずき閻魔',
        Select2: 'おはぎ閻魔',
        Select3: 'おいなり閻魔',
        Select4: 'こんにゃく閻魔',
        PicturePtn: '0'),
    '34': QuizQ(
        QID: '34',
        Picture: 'images/question/tate2.jpg',
        problem: '東京ドームシティ内にある、大人のための遊べるギャラリー「Gallery AaMo」。その「aMo」の由来は何でしょうか？',
        Select1: 'and More',
        Select2: 'amour propre',
        Select3: 'amoral',
        Select4: 'and modern',
        PicturePtn: '0'),
  };
}
// class QuizQ_List {
//   Map<String, QuizQ> list = {
//     '1': QuizQ(
//         QID: '1',
//         // Picture: 'images/Q076.jpeg',
//         Picture: 'images/tate.jpg',
//         problem:
//             '文京区にはとある小動物しか通れないほど急な坂であることにちなんで名付けられた坂があります。\nその小動物とは何でしょうか？',
//         Select1: '鼠',
//         Select2: '蛇',
//         Select3: '蛙',
//         Select4: '土竜',
//         PicturePtn: '1'),
//     '2': QuizQ(
//         QID: '2',
//         Picture: 'images/yoko.jpg',
//         problem:
//             '神社に祈願するときに奉納する「絵馬」。この絵馬のほとんどは馬の絵が描かれているが、湯島天神だけは他の動物が描かれている。その動物とは何でしょうか?',
//         Select1: '牛',
//         Select2: '豚',
//         Select3: '鳥',
//         Select4: '白ヘビ',
//         PicturePtn: '0'),
//     '3': QuizQ(
//         QID: '3',
//         Picture: 'images/Q003.jpg',
//         problem:
//         '江戸時代から続く飴細工の伝統を守り続けているお店が千駄木駅のほど近くにあります。その店舗名は次のうちどれでしょうか？',
//         Select1: 'あめ細工 吉原',
//         Select2: 'アメ細工 吉原',
//         Select3: '飴細工 吉原',
//         Select4: '雨細工 吉原',
//         PicturePtn: '0  '),
//   };
// }
